### ISSUE TITLE
Select Time in minutes

### ISSUE THREAD

**Issue by kevincollin** [bibekg/react-schedule-selector#18]
Hai @bibekg , thank you for the best schedule selector i know..
i have request about time hours selector, can the hour format be added minutes?

for example:
![Screen Shot 2020-01-10 at 10 38 32 AM](https://user-images.githubusercontent.com/44045377/72123882-5d7f7800-3395-11ea-9727-5d73977a126b.png)

**Comment by kevincollin** [comment]
Hai, thank you for the best schedule selector i know..
i have request about time hours selector, can the hour format be added minutes?

**Comment by bibekg** [comment]
Thanks for filing the issue. Yeah, a current limitation of this component is that it only supports hour-level resolution. Would love to improve this to minute-level res. I'll look into it!

**Comment by bibekg** [comment]
Putting together a PR for an approach where we add two new props: `hourlyChunks` (e.g. if you pass in `4`, it will give you `2:00pm`, `2:15pm`, `2:30pm`, `2:45pm`, etc.) and `timeFormat` which lets you format the time however you wish according to date-fn's formatting syntax (just like the existing `dateFormat` prop). Would this change capture what you're looking for?

**Comment by bibekg** [comment]
See PR #22
