### ISSUE TITLE
Updating the component when startDate changes

### ISSUE THREAD

**Issue by kyletsm** [bibekg/react-schedule-selector#24]
Hi I am having an issue about changing startDate in order to essentially cycle through weeks at a time. I have a button set up to change the startDate state and tried to forceUpdate in order to refresh the scheduling table but the dates do not change. When I console.log(this.state) the startDate was increased by a week.

**Comment by bibekg** [comment]
Interesting use case but unfortunately the component currently doesn't support it. 😞 The set of dates to render cells for is determined in the component's constructor. I've been considering a rehaul of the component architecture and will mark this as one of the things to address in it!

**Comment by bibekg** [comment]
Just published v3.0 which enables this use case! Let me know if you have any questions.
