### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by maddie-wang** [bibekg/react-schedule-selector#30]
when I npm install this plugin, I get:

https://paste.thezomg.com/75610/00978693/

Even when I've run npm i date-fn, I'm still running into this issue.

Do I have the wrong version of date-fn? I have date-fns@2.16.1

Please help me out! I would really appreciate it, this is a sexy version of when2meet!!

![image](https://user-images.githubusercontent.com/32725368/94195556-c7cf3e80-fe78-11ea-94a5-d9644862c5ae.png)

**Comment by maddie-wang** [comment]
the fix was:

npm install --save date-fns@1.30.1

**Comment by bibekg** [comment]
Glad it worked out! But it is a bit odd that the `date-fns` dependency didn't auto-install for you when you installed this library. 🤔
