### ISSUE TITLE
[Docs] I found typo in its documentation in npm

### ISSUE THREAD

**Issue by shawnscoding** [bibekg/react-schedule-selector#32]
It says :

```
numDays
type: number

description: The number of days to show, startin from today

required: no

default value: 7
```

I believe 'startin' should be starting in description.
If you allow me, I am happy to correct that and do PR to here.
However, let me know where is the source code of your docs in npm so that I can fix the typo.
thanks !!

**Comment by bibekg** [comment]
Thanks for catching this. I think this has been fixed since the latest publish! For future reference, the source should be the `README.md` in the root of this repo but they may be out of sync if the package hasn't been published since the README was changed.
